remote_theme: pmarsceill/just-the-docs

title: 电脑讨论与分享区
url: "https://computerdiscuss.github.io" # 

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

logo: "https://raw.githubusercontent.com/computerdiscuss/computerdiscuss.github.io/main/docs/logo/logo.png"
