remote_theme: pmarsceill/just-the-docs

title: 电脑讨论与分享区
url: "https://computerdiscuss.github.io" # 
logo: "/docs/11080499_954719721225450_7938736100747568296_o (1).jpg"


# Color scheme supports "light" (default) and "dark"
color_scheme: dark
