remote_theme: pmarsceill/just-the-docs

title: 电脑讨论与分享区
url: "https://computerdiscuss.github.io" # 

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

<link rel="shortcut icon" href="https://github.com/computerdiscuss/computerdiscuss.github.io/blob/main/docs/logo/logo.png" />
