remote_theme: pmarsceill/just-the-docs

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# Set a path/url to a logo that will be displayed instead of the title
logo: "docs/11080499_954719721225450_7938736100747568296_o (1).jpg"
